# Generated by Django 4.1.3 on 2022-12-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
